### ISSUE TITLE
Configure Reload Shortcut

### ISSUE THREAD

**Issue by drmmch** [howanghk/chrome-refresh-active-frame#1]
Is it possible to provide an option Page where you can configure the reload shortcut?
Alt+Shift+R works fine but it's not very handy to press all three keys.

**Comment by kschellercrowley** [comment]
@TildBJ You can simply update the manifest.json to the desired shortcut.

**Comment by howanghk** [comment]
@TildBJ you may configure the keyboard shortcut in chrome://extensions/shortcuts
